config/routes.rb
Rails.application.routes.draw do

  namespace 'admin' do
    get '/' => 'uploads#index'
    post '/uploads' => 'uploads#upload'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/admin/uploads/index.html.erb
<div class="container">
<%= form_tag admin_uploads_path, multipart: true do %>
    <%= hidden_field :upload, :type, value: 1 %>
    <%= file_field :upload, :file %>
    <%= submit_tag 'Upload' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActiveAdminDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>